import { stringify as stringifyCsv } from 'csv-stringify/sync';

// Settings keys we know bcl-convert rejects. Found in real samplesheets
// generated by BaseSpace / DRAGEN pipelines.
export const KNOWN_UNSUPPORTED_BCL_SETTINGS = new Set([
  'AutoDetectDemuxMode',
  'FastqcDownsampling',
]);

// Settings that require a UMI segment (U<n>) somewhere in OverrideCycles.
// bcl-convert errors if these are set without a corresponding U cycle.
const UMI_REQUIRED_SETTINGS = new Set([
  'TrimUMI',
  'Read1UMILength',
  'Read2UMILength',
]);

function effectiveOverrideCycles(parsed, override) {
  if (override !== undefined) return override;
  return parsed.sections[parsed.settingsKey]?.decoded?.OverrideCycles ?? '';
}

function hasUmiCycle(overrideCycles) {
  return /U\d+/.test(overrideCycles || '');
}

// Returns true if any row in the data section has a non-empty OverrideCycles cell.
// When this is true, bcl-convert forbids a global OverrideCycles in [Settings].
export function hasPerLaneOverrideCycles(parsedOrRows) {
  const rows = Array.isArray(parsedOrRows) ? parsedOrRows : parsedOrRows?.data;
  if (!rows || rows.length === 0) return false;
  const keys = Object.keys(rows[0] || {});
  const col = keys.find((k) => k.toLowerCase() === 'overridecycles');
  if (!col) return false;
  return rows.some((r) => String(r[col] ?? '').trim() !== '');
}

export function uniquePerLaneOverrides(rows) {
  if (!rows || rows.length === 0) return [];
  const keys = Object.keys(rows[0] || {});
  const col = keys.find((k) => k.toLowerCase() === 'overridecycles');
  if (!col) return [];
  const tally = new Map();
  for (const r of rows) {
    const v = String(r[col] ?? '').trim();
    if (!v) continue;
    tally.set(v, (tally.get(v) ?? 0) + 1);
  }
  return [...tally.entries()].map(([cycles, count]) => ({ cycles, count }));
}

export function findStrippedSettings(parsed, { drop = [], keepAll = false, overrideCycles, data } = {}) {
  if (keepAll) return [];
  const section = parsed.sections[parsed.settingsKey];
  if (!section?.decoded) return [];

  const extra = new Set(drop);
  const cycles = effectiveOverrideCycles(parsed, overrideCycles);
  const perLane = hasPerLaneOverrideCycles(data ?? parsed.data);
  // If per-lane is in use, treat "UMI present" as: any per-lane cycle has U.
  const umiCycle = perLane
    ? (data ?? parsed.data ?? []).some((r) => {
        const k = Object.keys(r).find((kk) => kk.toLowerCase() === 'overridecycles');
        return k && hasUmiCycle(r[k]);
      })
    : hasUmiCycle(cycles);

  const out = [];
  for (const [k, v] of Object.entries(section.decoded)) {
    if (KNOWN_UNSUPPORTED_BCL_SETTINGS.has(k) || extra.has(k)) {
      out.push({ key: k, value: v, reason: 'unsupported by bcl-convert' });
      continue;
    }
    if (k.toLowerCase() === 'overridecycles' && perLane) {
      out.push({ key: k, value: v, reason: 'per-lane OverrideCycles in [Data] forbids a global one' });
      continue;
    }
    if (!umiCycle && UMI_REQUIRED_SETTINGS.has(k)) {
      out.push({ key: k, value: v, reason: 'requires a U<n> segment in OverrideCycles' });
    }
  }
  return out;
}

export function serializeSampleSheet(parsed, overrides = {}) {
  // overrides: { data?, overrideCycles?, dropSettings?: string[], keepAllSettings?: boolean }
  const { sections, order, dataKey, settingsKey } = parsed;
  const stripSet = overrides.keepAllSettings
    ? new Set()
    : new Set([...KNOWN_UNSUPPORTED_BCL_SETTINGS, ...(overrides.dropSettings || [])]);

  const out = [];
  for (const name of order) {
    const section = sections[name];
    out.push(`[${name}]`);

    if (name === dataKey && overrides.data) {
      out.push(renderTabular(overrides.data));
    } else if (name === settingsKey) {
      out.push(renderSettings(section, overrides.overrideCycles, stripSet));
    } else if (section.rawLines.length) {
      out.push(section.rawLines.join('\n'));
    }
    out.push('');
  }

  if (overrides.data && !order.includes(dataKey)) {
    out.push(`[${dataKey}]`, renderTabular(overrides.data), '');
  }

  return out.join('\n').replace(/\n+$/, '\n');
}

function renderTabular(rows) {
  if (!rows || rows.length === 0) return '';
  const headers = Array.from(unionKeys(rows));
  return stringifyCsv(rows, { header: true, columns: headers });
}

function renderSettings(section, overrideCycles, stripSet) {
  const stripOverride = [...stripSet].some((k) => String(k).toLowerCase() === 'overridecycles');
  const lines = [];
  let wroteOverride = false;

  for (const line of section.rawLines) {
    const m = line.match(/^([^,]+),/);
    const key = m ? m[1].trim() : null;
    const keyLower = key?.toLowerCase();

    if (keyLower === 'overridecycles') {
      if (stripOverride) continue;
      if (overrideCycles !== undefined) {
        if (overrideCycles) lines.push(`OverrideCycles,${overrideCycles}`);
        wroteOverride = true;
        continue;
      }
      lines.push(line);
      continue;
    }

    if (key && stripSet.has(key)) continue;
    lines.push(line);
  }

  if (!wroteOverride && !stripOverride && overrideCycles) {
    lines.push(`OverrideCycles,${overrideCycles}`);
  }
  return lines.join('\n');
}

function unionKeys(rows) {
  const set = new Set();
  for (const r of rows) for (const k of Object.keys(r)) set.add(k);
  return set;
}
